### ISSUE TITLE
https://infinite.streamlit.app/ gives getting error: " Oh no. Error running app "

### ISSUE THREAD

**Issue by guruk** [Bklieger/infinite-bookshelf#54]
hi, i get 

Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/bklieger/infinite-bookshelf/issues/new).

when i try to connect to: https://infinite.streamlit.app/

it worked fine until yesterday.

What could be the reason?

Thanks
Christian

**Comment by Bklieger** [comment]
Hi Christian,

The app was temporarily offline after hitting resource limits due to high usage. Back online now: [infinite.streamlit.app](https://infinite.streamlit.app).

I will be investigating if recent changes have caused more frequent outages. You can also run the app locally with the provided instructions.

**Comment by guruk** [comment]
thanks

i try right now to install locally on my macbook

getting error that he dont find     exec(code, module.__dict__)

  File
"/Users/christianalbertmueller/Dropbox/Orga/Projects/code/AI/infinite-bookshelf-main/main.py",
line 3, in <module>

    from groq import Groq

ModuleNotFoundError: No module named 'groq'


but its installed..


i will try to get it run :) maybe chatgpt can help.. lol



thanks for ur work. love it!


best from Munich/ germany


christian

**Comment by Bklieger** [comment]
Did you install the package globally or in a virtual environment? Best practice is:

### Create virtual environment for your installs
~~~
python3 -m venv venv
~~~

### Activate virtual environment
~~~
source venv/bin/activate
~~~

### Install packages to that environment
~~~
pip3 install -r requirements.txt
~~~

### Run app
~~~
python3 -m streamlit run main.py
~~~

**Comment by guruk** [comment]
thanks,
with the help of Claude I got it fixed :)

best from munich
keep doing awesome.

christian

**Comment by Bklieger** [comment]
Great to hear! Thanks for the kind words, and have fun building!

Ben

**Comment by guruk** [comment]
its a pleasure.

i am coder since 40 years and working right now on my own little AI app.
I can imagine the challenges u go through, also the fun :)

Maybe we can work once together.
I made the app mydaysx (period app) in 2008.

Little bit out of focus for coding now myself
and unwilling to pay a coder . had some less cool experiences.
So either waiting for the right people or the moment I can finish my
prototype.

Anyhow, thats just sharing from a coder to a coder.

Guys, i wish you best, you do great, what u do is innovative, its working
and it does add value. Most importantly.

Christian
