### ISSUE TITLE
Repo of the new advanced version in beta: https://infinite.benjamin.sh/advanced

### ISSUE THREAD

**Issue by kuntal-c** [Bklieger/infinite-bookshelf#58]
Hello, this is not an issue but a request. Do you have the repo of the new advanced version in beta: https://infinite.benjamin.sh/advanced?

BTW excellent work!

**Comment by Bklieger** [comment]
Thank you! The code for the advanced mode is in this repository: [Advanced](https://github.com/Bklieger/infinite-bookshelf/blob/main/pages/advanced.py)
