### ISSUE TITLE
App Not Working 

### ISSUE THREAD

**Issue by ChrissyMoe** [Bklieger/infinite-bookshelf#61]
I've tried several times to launch infinite.streamlit.app and it says there's a error.

Error:

Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/bklieger/infinite-bookshelf/issues/new).

**Comment by Bklieger** [comment]
Please access using the new link: https://infinite.benjamin.sh

**Comment by ChrissyMoe** [comment]
Thank you!
